
#' CIBforecast
#'
#' A function for analysis stochastic transition matrices, and outputting the main statistics about them.
#' @keywords CIB
#' @export
#' @param Transitions A stochastic transition matrix (rows are presumed to add to 1). Can be generated by any of the function referenced in \code{\link{CIBTransitionCalculators}}
#' @note \code{\link{MakeScoreMatrix}} is probably the function you will need directly after this.
#' @return A list containing a long term forcast vector (a vector of probabilities of world states), a number representing the entropy of this vector, and a number representing the entropy production.
#' @author Alastair Jamieson Lane. <aja107@@math.ubc.ca>
#' @examples
#' data(antCIB)
#' boltzTrans<-LocalBoltzmann(antCIB)
#' forecast<- CIBforecast(boltzTrans)
#' 


CIBforecast<-function(Transitions){
  Eigs<-eigen(t(Transitions))
  Eigs<-Eigs[[2]][,1] #Grab the dominante eigenvector from the set of eigenvectors.
  Eigs<-Eigs/sum(Eigs) #normalise to make a probability
  Eigs<-abs(Eigs)
  names(Eigs)<-colnames(Transitions)
  Entropy<- -sum(Eigs*log(Eigs))
  EntropyProduction<- -sum(Eigs*rowSums(Transitions*log(Transitions+10^-100)))
  ReturnList<- list(Eigs,Entropy,EntropyProduction)
}
